config/routes.rb
Rails.application.routes.draw do
  root "scrps#index"
  get "scrps/index"
  resources :scrps
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scrp.rb
class Scrp < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scrps_controller.rb
class ScrpsController < ApplicationController
  before_action :set_scrp, only: [:show, :edit, :update, :destroy]
  require 'mechanize'

  # GET /scrps
  # GET /scrps.json
  def index
    @scrps = Scrp.all
    agent = Mechanize.new
    @values = []
    @vls = @values.join
    @vl = @vls.gsub!("\n ","")
    page = agent.get("https://www.nikkei.com/markets/worldidx/chart/nk225/")
    @elements=  page.search('li.m-trend_economic_table_list')
    @elements.each do |element|
      @values << element.inner_text
    end
  end

  # GET /scrps/1
  # GET /scrps/1.json
  def show
  end

  # GET /scrps/new
  def new
    @scrp = Scrp.new
    @scrps = Scrp.all

    agent = Mechanize.new
    values = []
    page = agent.get("https://www.nikkei.com/markets/worldidx/chart/nk225/")
    @elements=  page.search('li.m-trend_economic_table_list')
    @elements.each do |element|
      values << element.inner_text
    end
    @scrp = Scrp.new
    @scrp.name = Date.today
    @scrp.average = values
    @scrp.save
  end

  # GET /scrps/1/edit
  def edit
  end

  # POST /scrps
  # POST /scrps.json
  def create
    @scrp = Scrp.new(scrp_params)

    respond_to do |format|
      if @scrp.save
        format.html { redirect_to @scrp, notice: 'Scrp was successfully created.' }
        format.json { render :show, status: :created, location: @scrp }
      else
        format.html { render :new }
        format.json { render json: @scrp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scrps/1
  # PATCH/PUT /scrps/1.json
  def update
    respond_to do |format|
      if @scrp.update(scrp_params)
        format.html { redirect_to @scrp, notice: 'Scrp was successfully updated.' }
        format.json { render :show, status: :ok, location: @scrp }
      else
        format.html { render :edit }
        format.json { render json: @scrp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrps/1
  # DELETE /scrps/1.json
  def destroy
    @scrp.destroy
    respond_to do |format|
      format.html { redirect_to scrps_url, notice: 'Scrp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def scrape
    # agent = Mechanize.new
    # page = agent.get("https://www.nikkei.com/markets/worldidx/chart/nk225/")
    # @elements= page.search('span class="m-trend_economic_table_value a-tar"')
    #
    # elements.each do |ele|
    #   puts ele.inner_text
    # end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scrp
      @scrp = Scrp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scrp_params
      params.fetch(:scrp, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrps_helper.rb
module ScrpsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrapingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scrps/_form.html.erb
<%= form_with(model: scrp, local: true) do |form| %>
  <% if scrp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scrp.errors.count, "error") %> prohibited this scrp from being saved:</h2>

      <ul>
        <% scrp.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scrps/edit.html.erb
<h1>Editing Scrp</h1>

<%= render 'form', scrp: @scrp %>

<%= link_to 'Show', @scrp %> |
<%= link_to 'Back', scrps_path %>

app/views/scrps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scrps</h1>
<p><%= Time.now%></p>
<p><%= @vls %><p>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%# <%= @elements.inner_text %> %>
    <br />
    <br />

    <% @scrps.each do |scrp| %>
      <tr>
        <td><%= scrp.name %></td>
        <td><%= link_to 'Show', scrp %></td>
        <td><%= link_to 'Edit', edit_scrp_path(scrp) %></td>
        <td><%= link_to 'Destroy', scrp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scrp', new_scrp_path %>

app/views/scrps/new.html.erb
<h1>New Scrp</h1>

<%= render 'form', scrp: @scrp %>
<%= link_to 'Back', scrps_path %>

app/views/scrps/show.html.erb
<p id="notice"><%= notice %></p>

<%= @scrp.average %>

<br />
<br />
<%= link_to 'Edit', edit_scrp_path(@scrp) %> |
<%= link_to 'Back', scrps_path %>